project:
  type: website
  output-dir: docs
  resources:
    - downloads/**

website:
  title: "MBA Student Portfolio"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    css: styles.css
