project:
  type: website
  output-dir: docs
  resources:
    - downloads/**

website:
  title: "MBA Student Portfolio"
  navbar:
      left:
        - href: index.qmd
          text: About
        - href: resume.qmd
          text: Resume
        - href: education.qmd
          text: Education
        - href: casestudies.qmd
          text: Case Studies

  page-footer:
      left: "<span id='y'></span>Dr. Alina Pukhovskaya"
    
      
format:
  html:
    theme: cosmo
    toc-location: right
    page-layout: article
    css: styles.css
